
DROP DATABASE TOKENS;

CREATE DATABASE TOKENS;

\c tokens;
CREATE EXTENSION pgcrypto ;

CREATE user web_user with password 'foobar123!';

CREATE TABLE USERS (
	ID SERIAL,
	USER_IDENT TEXT NOT NULL UNIQUE,
	PASSWORD TEXT NOT NULL,
	NAME TEXT NOT NULL,
	WINNER BOOLEAN NOT NULL DEFAULT 'false',
	ADMIN BOOLEAN NOT NULL DEFAULT 'false',
	CODE_AT TIMESTAMP NOT NULL DEFAULT now(),
	FAILS INT NOT NULL DEFAULT 0
);
GRANT ALL ON USERS to web_user;

CREATE TABLE EVENTS (
	EVENT_IDENT	TEXT UNIQUE NOT NULL
);
GRANT ALL ON events to web_user;

CREATE TABLE TOKENS (
	CODE TEXT NOT NULL UNIQUE, --Slated Hash of the token code. 
	DESCRIPTION TEXT NOT NULL UNIQUE,
	QTY INT NOT NULL DEFAULT 1, --Create how many ticket when token is redeemed.  
	MULTI INT DEFAULT NULL, --How many users may redeem.
	TAG TEXT, 
	DEC INT NOT NULL DEFAULT 0,
	EVENT TEXT REFERENCES EVENTS (EVENT_IDENT)
);
GRANT ALL ON tokens to web_user;

CREATE TABLE TICKETS (
	ID	SERIAL, 
	USER_IDENT TEXT NOT NULL REFERENCES USERS (USER_IDENT),
	CREATED_AT TIMESTAMP DEFAULT now(), 
	CODE TEXT NOT NULL REFERENCES TOKENS (CODE)
);
GRANT ALL ON tickets to web_user;
GRANT ALL ON tickets_id_seq to web_user;

CREATE TABLE LOG_TYPES (
	TYPE	TEXT NOT NULL UNIQUE
);

INSERT INTO LOG_TYPES (TYPE) VALUES ('token_try');

CREATE TABLE LOGS (
	ID	SERIAL,
	TYPE	TEXT,
	CREATED_AT TIMESTAMP DEFAULT now(), 
	SOURCE	TEXT,
	USER_IDENT TEXT REFERENCES USERS (USER_IDENT),
	REQUEST TEXT,
	HEADERS TEXT
);
GRANT ALL ON logs to web_user;
GRANT ALL ON logs_id_seq to web_user;



CREATE TABLE TEAMS (
	EVENT_IDENT TEXT NOT NULL REFERENCES EVENTS (EVENT_IDENT),
	TEAM_IDENT TEXT NOT NULL UNIQUE
);
GRANT ALL ON teams to web_user;

CREATE TABLE USER_TEAMS (
	TEAM_IDENT TEXT NOT NULL REFERENCES TEAMS (TEAM_IDENT),
	USER_IDENT TEXT NOT NULL REFERENCES USERS (USER_IDENT)
);
GRANT ALL ON user_teams to web_user;


